ReversiMvcApp/Models/Game.cs
namespace ReversiMvcApp.Models
{
    public class Game
    {
        public int ID { get; set; }
        public string Description { get; set; }
        public Color[,] Board { get; set; }
        public string Token { get; set; }
        public string Player1Token { get; set; }
        public string Player2Token { get; set; }
        public Color PlayerTurn { get; set; }
    }
}

ReversiMvcApp/Controllers/GameController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using ReversiMvcApp.Data;
using ReversiMvcApp.Models;
using System.Collections.Generic;
using System.Net;
using System.Net.Http;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;

namespace ReversiMvcApp.Controllers
{
    public class GameController : Controller
    {

        public string API_BASE_URL { get; set; }
        public ReversiDbContext _context { get; set; }
        private readonly ApiAccessLayer _api;

        public GameController(IConfiguration configuration, ReversiDbContext context, ApiAccessLayer api)
        {
            API_BASE_URL = configuration.GetValue<string>("RestApiUrl");
            _context = context;
            _api = api;
        }

        // GET: GameController
        [Authorize(Roles = "Player,Mediator,Administrator")]
        public async Task<ActionResult> Index()
        {
            ClaimsPrincipal currentUser = this.User;
            var currentUserID = currentUser.FindFirst(ClaimTypes.NameIdentifier).Value;

            Game game = await _api.GetGameFromPlayer(currentUserID);

            if (game != null)
            {
                return Redirect("/Game/Play");
            }

            List<Game> games = await _api.GetAvailableGames();
            return View(games);
        }

        // GET: GameController/Create
        [Authorize(Roles = "Player,Mediator,Administrator")]
        public async Task<ActionResult> Create()
        {
            ClaimsPrincipal currentUser = this.User;
            var currentUserID = currentUser.FindFirst(ClaimTypes.NameIdentifier).Value;

            Game game = await _api.GetGameFromPlayer(currentUserID);

            if (game != null)
            {
                return Redirect("/Game/Play");
            }

            return View();
        }

        // POST: GameController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Player,Mediator,Administrator")]
        public async Task<ActionResult> Create(string description)
        {
            ClaimsPrincipal currentUser = this.User;
            var currentUserID = currentUser.FindFirst(ClaimTypes.NameIdentifier).Value;

            Game game = await _api.GetGameFromPlayer(currentUserID);

            if (game != null)
            {
                return Redirect("/Game/Play");
            }

            await _api.CreateGame(currentUserID, description);

            return RedirectToAction(nameof(Index));
        }

        // PUT: GameController/Join
        [HttpPost]
        public async Task<ActionResult> Join(int gameId)
        {
            ClaimsPrincipal currentUser = this.User;
            var currentUserID = currentUser.FindFirst(ClaimTypes.NameIdentifier).Value;

            await _api.JoinGame(gameId, currentUserID);
            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = "Player,Mediator,Administrator")]
        public async Task<ActionResult> Play()
        {
            ClaimsPrincipal currentUser = this.User;
            var currentUserID = currentUser.FindFirst(ClaimTypes.NameIdentifier).Value;

            Game game = await _api.GetGameFromPlayer(currentUserID);

            if (game == null)
            {
                return Redirect("/Game");
            }

            return View(game);
        }

        public class NewGame
        {
            public string PlayerToken { get; set; }
            public string Description { get; set; }
        }

    }
}

ReversiMvcApp/Views/Game/Create.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<form method="post">
    <label>Omschrijving:</label>
    <input type="text" name="description" />
    <button type="submit">Aanmaken</button>
</form>

ReversiMvcApp/Views/Game/Index.cshtml
@model List<Game>

<p>Beschikbare spellen:</p>

@foreach (Game item in Model)
{
            <form method="post" action="@Url.Action("Join", "Game")">
                <p>@Html.DisplayFor(modelItem => item.Description)</p>       
                <input type="hidden" name="gameId" value="@Html.DisplayFor(modelItem => item.ID)">
                <button type="submit">Join game</button>
            </form>

}

<a asp-action="Create">Start een nieuw spel</a>

ReversiMvcApp/Views/Game/Play.cshtml
@using Newtonsoft.Json
@model Game

@{
    string translated = @Model.PlayerTurn switch
    {
        Color.None => "Geen",
        Color.Black => "Zwart",
        Color.White => "Wit"
    };
}

<script type="text/javascript">
    $(document).ready(function () {
       Game.init(() => console.log("Game initiated"));
       Game.Reversi.setGame(@Html.Raw(JsonConvert.SerializeObject(@Model)));
    });
</script>

<div class="reversi-turn">
    <p>Nu aan de beurt: <strong id="reversi-turn">@translated</strong></p>
</div>

<div>
   <div class="reversi-board">
</div>

<div id="reversi-cat-fact"></div>